[package]
name = "language"
version = "0.1.0"
edition = "2024"

[dependencies]
ipa = { path = "../ipa" }
data = { path = "../data" }
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
time.workspace = true
pest = "2.8.6"
pest_derive = "2.8.6"
tracing.workspace = true
rand = "0.10.1"
jsonschema = "0.46.2"
base62 = "2.0"


[dev-dependencies]
cucumber.workspace = true
tokio.workspace = true
tempfile = "3"

[lints]
workspace = true

[[test]]
name = "sound_matcher_cucumber"
harness = false

[[test]]
name = "syllabification_cucumber"
harness = false

