[package]
name = "ipa"
version = "0.1.0"
edition = "2024"

[dependencies]
data = { path = "../data" }
thiserror.workspace = true
serde.workspace = true
unicode-normalization = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
cucumber.workspace = true
tokio.workspace = true

[[test]]
name = "sequence_cucumber"
harness = false

